{"time":"2025-09-14T22:20:48.6392441+02:00","level":"INFO","msg":"stream: starting","core version":"0.19.5","symlink path":"c:\\Users\\aarus\\Desktop\\Github\\DIKU-NLP\\week-37\\wandb\\run-20250914_222048-qvfsxwco\\logs\\debug-core.log"}
{"time":"2025-09-14T22:20:48.7499809+02:00","level":"INFO","msg":"created new stream","id":"qvfsxwco"}
{"time":"2025-09-14T22:20:48.7499809+02:00","level":"INFO","msg":"stream: started","id":"qvfsxwco"}
{"time":"2025-09-14T22:20:48.7499809+02:00","level":"INFO","msg":"sender: started","stream_id":"qvfsxwco"}
{"time":"2025-09-14T22:20:48.7499809+02:00","level":"INFO","msg":"writer: Do: started","stream_id":"qvfsxwco"}
{"time":"2025-09-14T22:20:48.7499809+02:00","level":"INFO","msg":"handler: started","stream_id":"qvfsxwco"}
{"time":"2025-09-14T22:20:49.1197701+02:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-09-14T22:27:38.9423841+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.0.122:64519->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-09-14T22:29:31.9752516+02:00","level":"INFO","msg":"Pausing system monitor"}
